[package]
name = 'vc-follow'
version = '0.1.0'
edition = '2021'

[dependencies]
chrono = '0.4'
structopt = "0.3"

[dependencies.uuid]
version = '0.8'
features = [
    'serde',
    'v4',
    'stdweb',
]
